// Runs as a separate process via child_process.fork() in server.js.
// Even though Skia rendering is lightweight compared to the old
// Chrome-based pipeline, this isolation is kept deliberately: if
// anything unexpected crashes mid-render, only this one job dies -
// the main server and every other in-flight request keep running.

const os = require('os');
const path = require('path');
const { generateSceneJSON, generateEditedSceneJSON } = require('./mistralClient');
const { renderLongFormVideo } = require('./longVideoOrchestrator');
const { prefetchBeatImages, cleanupBeatImages } = require('./imagePrefetch');
const { prefetchNarration, cleanupNarration } = require('./narrationPrefetch');
const { muxNarrationOntoVideo } = require('./audioMux');

let currentJobId = null;

/**
 * process.send() is asynchronous - calling process.exit() right after
 * it risks the message never actually reaching the parent. This waits
 * for the actual flush callback before exiting. (Confirmed necessary
 * and confirmed fixed via direct testing in the previous architecture
 * - same fix carried over here since the risk is identical.)
 */
function sendAndFlush(message) {
  return new Promise((resolve) => {
    if (!process.send) return resolve();
    process.send(message, () => resolve());
  });
}

process.on('message', async ({ jobId, prompt, targetDurationSeconds, parentSceneJSON }) => {
  currentJobId = jobId;

  try {
    await sendAndFlush({ type: 'status', jobId, status: 'writing_scenes' });

    // If this job was created as an edit of a previous one, its
    // scene JSON is generated by REVISING the parent's, not by
    // designing a brand new video from scratch - a completely
    // different Mistral prompt (see buildMistralEditSystemPrompt).
    const sceneJSON = parentSceneJSON
      ? await generateEditedSceneJSON(parentSceneJSON, prompt, targetDurationSeconds || 12)
      : await generateSceneJSON(prompt, targetDurationSeconds || 12);

    // sceneJSON (unmodified) goes back to the parent HERE - that's what
    // gets persisted to Supabase and reused as edit context later, so
    // it must never contain local temp file paths. Image prefetch below
    // produces a SEPARATE render-only copy for renderLongFormVideo.
    await sendAndFlush({ type: 'scenes_ready', jobId, sceneJSON });
    await sendAndFlush({ type: 'status', jobId, status: 'rendering', progress: 0 });

    // Narration FIRST - it overrides each spoken beat's `duration` to
    // match how long the audio actually takes to say, which the world
    // timeline (and therefore image prefetch, which is keyed by beat
    // index rather than timing) needs to already reflect.
    const { sceneJSON: narratedSceneJSON, audioFiles } = await prefetchNarration(sceneJSON, jobId);
    const renderSceneJSON = await prefetchBeatImages(narratedSceneJSON, jobId);

    const renderedPath = await renderLongFormVideo(jobId, renderSceneJSON, (pct) => {
      if (process.send) process.send({ type: 'progress', jobId, progress: pct });
    });

    const localFilePath = await muxNarrationOntoVideo(renderedPath, renderSceneJSON, audioFiles, jobId, path.join(os.tmpdir(), 'shortform-renders'));

    await sendAndFlush({ type: 'render_complete', jobId, localFilePath });
  } catch (err) {
    await sendAndFlush({ type: 'failed', jobId, error: String((err && err.message) || err) });
  } finally {
    cleanupBeatImages(jobId);
    cleanupNarration(jobId);
    process.exit(0);
  }
});

process.on('uncaughtException', async (err) => {
  await sendAndFlush({ type: 'failed', jobId: currentJobId, error: String((err && err.message) || err) });
  process.exit(1);
});
